---
# cf. https://github.com/weaveworks/eksctl/tree/master/examples
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: jlabs-pp-eks
  region: eu-west-1

vpc:
  cidr: 10.10.0.0/16
  autoAllocateIPv6: true

nodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 1
    maxSize: 2
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
