- hosts: "{{ target|default('es_instances') }}"
  # become: yes
  tasks:
    - debug:
       msg: "ip : {{ ansible_default_ipv4.address }}"
    - name: Wait for elasticsearch to startup
      wait_for:
        host: "{{ ansible_default_ipv4.address }}"
        port: 9200
        delay: 5
        connect_timeout: 1

    # - name: restart elasticsearch
    #   service:
    #     name: elasticsearch
    #     state: restarted
    #     enabled: yes

    # - name: Check metrics reqs
    #   uri:
    #     url: "http://{{ ansible_default_ipv4.address }}:9200/_prometheus/metrics"
    #     method: GET
    #     # user: "metrics"
    #     # password: "metrics"

# systemctl
# journalctl
# systemctl status elasticsearch.service
# systemctl start elasticsearch.service
