---
- hosts: "{{ target|default('all') }}"
  become: yes

  tasks:
    - shell: >-
        rm /var/log/elasticsearch/*
      args:
        warn: no
      changed_when: False
    - name: restart elasticsearch
      service:
        name: elasticsearch
        state: restarted
        enabled: yes


