---
- hosts: "{{ target | default('all:!bastion') }}"
  any_errors_fatal: true
  become: yes

  tasks:
# iptables -A INPUT -s <ip> -p tcp --destination-port 9100 -j DROP
    - iptables:
        action: "append"
        chain: "INPUT"
        source: "{{ item }}"
        protocol: "tcp"
        destination_port: 9100
        jump: "DROP"
      with_items: "{{ monitor_blocked_ips }}"

# iptables -A INPUT -s <ip> -p tcp --destination-port 9172 -j DROP
    - iptables:
        action: "append"
        chain: "INPUT"
        source: "{{ item }}"
        protocol: "tcp"
        destination_port: 9172
        jump: "DROP"
      with_items: "{{ monitor_blocked_ips }}"
