# ansible-playbook plays/maintain/nomad_run_jobs.yml -e job=svc-api/svc-api
---
- hosts: "{{ target | default('nomad-master-0') }}"
  any_errors_fatal: true
  become: yes

  vars:
    jobs_dir: "/root/nomad/jobs"

  tasks:
    - name: run metrics-nomad
      shell: >-
        nomad run {{ jobs_dir }}/system/metrics-nomad.hcl
      register: res

    - name: run svc-example
      shell: >-
        nomad run {{ jobs_dir }}/svc-example/svc-example.hcl
      register: res
