---
- hosts: "{{ target|default('nomad-masters,nomad-workers') }}"
  become: yes
  tasks:
    - shell: >-
        nomad status
      register: res
      changed_when: False
      # args:
      #   warn: no

    - debug:
        msg : "{{ res.stdout }}"
