# ansible-playbook plays/maintain/nomad_restart_job.yml -e job=svc-api/svc-api
---
- hosts: "{{ target | default('nomad-master-0') }}"
  any_errors_fatal: true
  become: yes

  vars:
    jobs_dir: "/root/nomad/jobs"

  tasks:
    - name: stop the job
      shell: >-
        nomad stop -purge {{ job.split('/')[1] }}
      register: res
      ignore_errors: yes

    - debug:
        msg: "{{ res }}"

    - name: run the job
      shell: >-
        nomad run {{ jobs_dir }}/{{ job }}.hcl
      register: res

    - debug:
        msg: "{{ res }}"
