# ansible-playbook plays/maintain/vault_push_config.yml --tags secrets
---
- hosts: "{{ target | default('nomad-master-0') }}"
  become: yes

  vars_files:
    - "{{ secrets_dir }}/docker-env/commons.yml"
    - "{{ secrets_dir }}/docker-env/node-config.yml"

  tasks:
    - name: create policies dir
      file:
        path: "{{ root_dir }}/vault/policies"
        state: directory
        force: yes
      tags: policies

    - name: create policy nomad-jobs
      copy:
        src: "{{ playbook_dir }}/../../files/vault/policies/nomad-jobs.hcl"
        dest: "{{ root_dir }}/vault/policies/nomad-jobs.hcl"
        mode: 0644
      tags: policies

    - name: write policy nomad-jobs
      shell: >-
        vault policy-write nomad-jobs {{ root_dir }}/vault/policies/nomad-jobs.hcl
      register: res
      environment: "{{ vault_env }}"
      tags: policies
    - debug:
        msg: "{{ res }}"
      tags: policies

    - name: create secrets_tmp dir
      file:
        path: "{{ root_dir }}/vault/secrets_tmp"
        state: directory
        force: yes
      tags: secrets

    - name: create secret node-config tmp file
      copy:
        content: "{{ node_config | to_json }}"
        dest: "{{ root_dir }}/vault/secrets_tmp/node-config.json"
        mode: 0644
      tags: secrets

    - name: write secret node-config
      shell: >-
        vault write secret/node-config value=@{{ root_dir }}/vault/secrets_tmp/node-config.json
      register: res
      environment: "{{ vault_env }}"
      tags: secrets
    - debug:
        msg: "{{ res }}"
      tags: secrets

    - name: remove secret node-config tmp file
      file:
        path: "{{ root_dir }}/vault/secrets_tmp/node-config.json"
        state: "absent"
        force: yes
      tags: secrets

    - name: write secret node-proxies
      shell: >-
        vault write secret/node-proxies value={{ node_proxies }}
      register: res
      environment: "{{ vault_env }}"
      tags: secrets
    - debug:
        msg: "{{ res }}"
      tags: secrets
