---
node_config:

  # REDIS
  # SVC_EXAMPLE_REDIS_HOST: svc-example-redis.jlabs-pp-eu-west-1.internal.jdxlabs.com
  # SVC_EXAMPLE_REDIS_PORT: 6379

  # SERVICES
  SVC_EXAMPLE:
    # host: http://svc-example-microservices-svc-example.service.dc1.consul
    host: http://example.svc.jin-pp-eu-west-1.jdxlabs.com
    port: 11201
    jwt_passphrase: 9waWNDbGllbnQbXlBd2Vzb21lVG=
    jwt_secret: pY2VASmluFuYWdlcdG9waWNzTWlNlcnZ

  # COMMONS
  AWS:
    api:
      region: eu-west-1
      version: latest
