# ansible-playbook plays/apply/apply_consul.yml
---
- hosts: "consul-servers-bootstrap,logstore"
# usefull to join clients to servers, when they are applied individually

- hosts: "{{ target|default('all:!bastion:!maintainer') }}"
  become: yes
  # pre_tasks:
  #   - apt_repository:
  #       repo: "deb http://httpredir.debian.org/debian stretch-backports main contrib non-free"
  #       update_cache: yes
  tags:
    - unbound
  roles:
    - unbound

- hosts: "{{ target|default('all:!bastion:!maintainer') }}"
  become: yes
  tags:
    - consul
  roles:
    - consul-agent
    # - consul-role
