---
#- src: https://github.com/awslabs/amazon-ecr-credential-helper
#  version: master
#  name: ecr-helper

#- src: https://github.com/prometheus/statsd_exporter
#  version: master
#  name: statsd_exporter

# - src: https://github.com/WeScale/consul-role
#   version: "master"
