# ansible-playbook plays/apply/apply_monitoring.yml
---
- hosts: all:!bastion
  become: yes
  tags:
    - agents
  roles:
    - consul-agent
    - prometheus-node

- hosts: monitor
  become: yes
  vars_files:
    - "{{ secrets_dir }}/grafana.yml"
  tags:
    - promaster
  roles:
    - prometheus-master
    - grafana
