# ansible-playbook plays/apply/apply_monitoring_es.yml
---
- hosts: "{{ target|default('es_instances') }}"
  become: yes
  tags:
    - es_plugin
  handlers:
    - name: restart elasticsearch
      service:
        name: elasticsearch
        state: restarted
        enabled: yes
  tasks:
    - shell: >-
        /usr/share/elasticsearch/bin/elasticsearch-plugin list
      register: "installed_plugins"
      changed_when: false
    - set_fact:
        plugin_is_installed: "{{ 'prometheus-exporter' in installed_plugins.stdout }}"
        es_plugin_reinstall: "{{ es_plugin_reinstall | default(false) }}"

    - name: Remove ES monitoring plugin
      shell: >-
        /usr/share/elasticsearch/bin/elasticsearch-plugin remove prometheus-exporter --silent
      when: "plugin_is_installed and es_plugin_reinstall"
      notify: restart elasticsearch

    - name: Install ES monitoring plugin
      shell: >-
        /usr/share/elasticsearch/bin/elasticsearch-plugin install -b
        https://distfiles.compuscene.net/elasticsearch/elasticsearch-prometheus-exporter-5.5.2.0.zip
      when: "not plugin_is_installed or es_plugin_reinstall"
      notify: restart elasticsearch

- hosts: "{{ target|default('es_instances') }}"
  become: yes
  serial: 1
  tags:
    - consul_restart
  tasks:
    - set_fact:
        instance_type: "{{ inventory_hostname | regex_replace('^(?P<cluster>.+)-instance-(?P<type>.+)-(?P<nb>\\d+)$', '\\g<type>') }}"
    - file:
        path: /etc/consul.d/es-export.json
        state: absent
    - copy:
        dest: "/etc/consul.d/es-export.json"
        content:
          {
            "service": {
              "name": "es_exporter_{{ instance_type }}",
              "tags": [
                "monitor-es",
                "es",
                "cluster",
                "metrics_path=/_prometheus/metrics"
              ],
              "enableTagOverride": false,
              "check": {
                "interval": "10s",
                "timeout": "1s"
              },
              "port": 9200
            }
          }

    - name: restart consul
      service:
        name: consul
        state: restarted
        enabled: yes
