# ansible-playbook plays/apply/apply_logrotate_es.yml -e target=es_instances
- hosts: "{{ target|default('es_instances') }}"
  become: yes
  gather_facts: no

  tasks:

    - name: install logrotate
      apt:
        name: logrotate
        update_cache: yes

    - name : apply logrotate config for es
      template:
        src: "../../templates/logrotate-es.j2"
        dest: "/etc/logrotate.d/elasticsearch"

    - name: crontab - disable mailto option
      cron:
        name: "MAILTO"
        minute: 'MAILTO=""'
        hour: ""
        day: ""
        month: ""
        weekday: ""
        job: ""

    - name: crontab - boost logrotate frequency for es, to avoid errors floods dramas
      cron:
        name: "boost logrotate frequency for es"
        minute: "*/180"
        hour: "*"
        job: "/usr/sbin/logrotate -f /etc/logrotate.d/elasticsearch"
