- hosts: localhost
  become: no
  vars_files:
    - "../../{{ target_name }}/inventories/group_vars/{{ cluster_alias }}_config.yml"
  tags:
    - attach_snapshots
  tasks:
    - debug:
        msg : "url : {{ es_url }}/_snapshot/{{ target_name }}-{{ target_region }}-{{ cluster_alias }}-snapshots"

    - name: Attach snapshots to S3
      uri:
        url: "{{ es_url }}/_snapshot/{{ target_name }}-{{ target_region }}-{{ cluster_alias }}-snapshots"
        method: PUT
        body: '{"type":"s3","settings":{"location":"{{ target_name }}-{{ target_region }}-{{ cluster_alias }}-snapshots","region":"{{ target_region }}","compress":true}}'
        body_format: json
        headers:
          Content-Type: "application/json"
