---
- src: https://github.com/elastic/ansible-elasticsearch
  version: master
  name: es-role
- src: https://github.com/prometheus/node_exporter
  version: master
  name: prometheus-exporter
- src: https://github.com/vvanholl/elasticsearch-prometheus-exporter
  version: master
  name: es-prometheus-exporter
- src: https://grafana.com/dashboards/266
  version: master
  name: es-grafana
